### ISSUE TITLE
spaces folder and file name

### ISSUE THREAD

**Issue by evanwill** [drbutterfield/theory-draft-1#1]
@drbutterfield looks like the magical reorganization is starting up! 

I noticed you added a bunch of new folders--I wanted to mention that you should avoid spaces in all folder and file names, it makes things easier when building the website. You can replace the spaces with `-` or `_`. If you rename the folders in your local version and push it, it will be updated on GitHub as well (of course). 

thanks

**Comment by smbutterfield** [comment]
@evanwill Good catch. I did the folder reorganization using Windows out of habit, and then just defaulted to my normal folder naming habits. I've fixed those and finished organizing all of the new files.
